name: 'pvm update'

on:
  push:
    branches:
      - 'master'

env:
  PVM_LL: silly

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - run: npm exec pvm update
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
