name: Pull Request

on:
  pull_request:
    branches:
      - master
      - next
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: NX Cache
        uses: actions/cache@v2.1.4
        with:
          path: ./.cache
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: |
          npm ci
        env:
          CI: true
      - name: Build
        run: |
          npm run build
        env:
          CI: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: NX Cache
        uses: actions/cache@v2.1.4
        with:
          path: ./.cache
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: |
          npm ci
        env:
          CI: true
      - name: Lint
        run: |
          npm run lint
        env:
          CI: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: NX Cache
        uses: actions/cache@v2.1.4
        with:
          path: ./.cache
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: |
          npm ci
        env:
          CI: true
      - name: Test
        run: |
          npm test
        env:
          CI: true
