name: Pull Request

on:
  pull_request:
    branches:
      - master
env:
  PVM_LL: silly

jobs:
  mark-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - run: npm exec pvm mark-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm test
